# Generated by Django 4.2.16 on 2024-12-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_replied_thread', to='forum.reply'),
        ),
    ]
