# Generated by Django 4.2.16 on 2024-12-12 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0007_userpostcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpostcount',
            old_name='total_posts',
            new_name='total_count',
        ),
        migrations.AlterField(
            model_name='userpostcount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
