# Generated by Django 4.2.16 on 2024-12-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_rename_total_posts_userpostcount_total_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='post_count',
        ),
    ]
