# Generated by Django 4.2.16 on 2024-12-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_remove_userprofile_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostcount',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpostcount',
            name='thread_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
