# Generated by Django 4.2.16 on 2024-12-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_userpostcount_comment_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostcount',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='userpostcount',
            name='thread_count',
        ),
    ]
