# Generated by Django 4.2.16 on 2024-12-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
