# Generated by Django 4.2.16 on 2024-12-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('program_organized_by', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
    ]
