# Generated by Django 4.2.16 on 2026-05-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_carousel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('about_left', 'About Left Image'), ('about_right', 'About Right Image'), ('feature_main', 'Feature Main Image')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='homepage/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
