# Generated by Django 4.2.16 on 2026-09-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Empowering communities through education', max_length=200)),
                ('lead', models.TextField(blank=True, help_text='Short intro under the title.', max_length=500)),
                ('story', models.TextField(help_text='Main story. Separate paragraphs with a blank line.')),
                ('image', models.ImageField(blank=True, help_text='Photo shown beside the figures.', upload_to='about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About page',
            },
        ),
        migrations.AlterModelOptions(
            name='homepagemedia',
            options={'verbose_name': 'Landing page image', 'verbose_name_plural': 'Landing page images'},
        ),
        migrations.AlterField(
            model_name='homepagemedia',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Describe the photo for screen readers and search engines.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagemedia',
            name='key',
            field=models.CharField(choices=[('hero_main', 'Landing page — main hero image (large, portrait)'), ('hero_side', 'Landing page — small side image (square)'), ('video_cover', 'Landing page — video cover image (landscape)')], max_length=50, unique=True, verbose_name='position'),
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 15 or 18k+', max_length=20)),
                ('label', models.CharField(help_text='e.g. chapters across Nepal', max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='web.aboutpage')),
            ],
            options={
                'verbose_name': 'figure',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g. 2011 or Today', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='web.aboutpage')),
            ],
            options={
                'verbose_name': 'timeline entry',
                'verbose_name_plural': 'timeline',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
