# Generated by Django 4.2.16 on 2026-09-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_seed_about_page_and_rename_media_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='book-open', help_text='Icon name from lucide.dev/icons, e.g. "library", "users", "mic".', max_length=40)),
                ('title', models.CharField(max_length=80)),
                ('text', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='web.aboutpage')),
            ],
            options={
                'verbose_name': "'What we do' card",
                'verbose_name_plural': "'What we do' cards",
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
