# Generated by Django 4.2.16 on 2026-09-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_seed_about_pillars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Landing page slide', 'verbose_name_plural': 'Landing page slideshow (optional — replaces the hero images when added)'},
        ),
    ]
