# Generated by Django 4.2.16 on 2026-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_carousel_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagemedia',
            name='key',
            field=models.CharField(choices=[('hero_main', 'Landing page — main hero image (large, portrait)'), ('hero_side', 'Landing page — small side image (square)'), ('video_cover', 'Landing page — video cover image (landscape)'), ('default_cover', 'Default background photo — login/sign-up, social previews, and pages without their own photo')], max_length=50, unique=True, verbose_name='position'),
        ),
    ]
