# Generated by Django 4.2.16 on 2026-09-24 11:30

from django.db import migrations, models
import dpl.storage


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_default_cover_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_proof',
            field=models.ImageField(blank=True, storage=dpl.storage.private_storage, upload_to='donation_proofs/'),
        ),
    ]
