# Generated by Django 4.2.16 on 2024-12-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('Past_position', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='candidate_profiles/')),
                ('citizenship_document', models.FileField(upload_to='citizenship_documents/')),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
