# Generated by Django 4.2.16 on 2024-12-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electioncandidate',
            name='position',
        ),
    ]
