# Generated by Django 4.2.16 on 2024-12-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_electioncandidate_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncandidate',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Senior Vice-President', 'Senior Vice-President'), ('Vice-President', 'Vice-President'), ('Secretary General', 'Secretary General'), ('Treasurer', 'Treasurer'), ('Director', 'Director')], default='choose', max_length=50),
        ),
    ]
