# Generated by Django 4.2.16 on 2024-12-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_electioncandidate_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electioncandidate',
            old_name='Past_position',
            new_name='past_position',
        ),
    ]
