# Generated by Django 4.2.16 on 2026-09-24 11:30

from django.db import migrations, models
import dpl.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_past_position_electioncandidate_past_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioncandidate',
            name='citizenship_document',
            field=models.FileField(storage=dpl.storage.private_storage, upload_to='citizenship_documents/'),
        ),
        migrations.AlterField(
            model_name='electioncandidate',
            name='payment_screenshot',
            field=models.ImageField(storage=dpl.storage.private_storage, upload_to='payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='electioncandidate',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=dpl.storage.private_storage, upload_to='candidate_profiles/'),
        ),
    ]
