# Generated by Django 4.2.16 on 2024-12-03 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentBranch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='branches/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DamakBranchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('member_image', models.ImageField(upload_to='branch_team/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_branches', to='branches.parentbranch')),
            ],
        ),
    ]
