# Generated by Django 4.2.16 on 2024-12-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DamakBranchTeam',
            new_name='BranchTeam',
        ),
    ]
