# Generated by Django 4.2.16 on 2024-12-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_parentbranch_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchteam',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_teams', to='branches.parentbranch'),
        ),
    ]
