# Generated by Django 4.2.16 on 2024-12-04 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branchteam_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('program_date', models.DateField()),
                ('coordinator_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='programs/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='branches.parentbranch')),
            ],
        ),
    ]
