# Generated by Django 4.2.16 on 2026-09-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_programimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchteam',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='parentbranch',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AddField(
            model_name='branchteam',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='branchteam',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branchteam',
            name='member_type',
            field=models.CharField(choices=[('board', 'Current Board'), ('charter_president', 'Charter President'), ('past_president', 'Past President'), ('advisor', 'Advisor')], default='board', max_length=20),
        ),
        migrations.AddField(
            model_name='branchteam',
            name='term',
            field=models.CharField(blank=True, help_text='e.g. 2024-2026', max_length=50),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='branch_type',
            field=models.CharField(choices=[('chapter', 'Chapter'), ('teens', 'Teens Wing'), ('national_board', 'National Board'), ('senate', 'DPL Senate')], default='chapter', max_length=20),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive branches are hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps link to the library'),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='For a Teens wing, the chapter it belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wings', to='branches.parentbranch'),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='province',
            field=models.CharField(blank=True, choices=[('koshi', 'Koshi'), ('madhesh', 'Madhesh'), ('bagmati', 'Bagmati'), ('gandaki', 'Gandaki'), ('lumbini', 'Lumbini'), ('karnali', 'Karnali'), ('sudurpashchim', 'Sudurpashchim')], max_length=20),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used in the web address, e.g. /chapters/damak/', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='parentbranch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='branchteam',
            name='member_image',
            field=models.ImageField(blank=True, upload_to='branch_team/'),
        ),
        migrations.AlterField(
            model_name='parentbranch',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='branches/'),
        ),
        migrations.CreateModel(
            name='BranchGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='branch_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='branches.parentbranch')),
            ],
            options={
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
    ]
