# Generated by Django 4.2.16 on 2026-09-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_branch_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentbranch',
            name='in_about_menu',
            field=models.BooleanField(default=False, help_text='List this page under the About menu (e.g. DPL, DPL Nepal, boards).'),
        ),
        migrations.AlterField(
            model_name='parentbranch',
            name='branch_type',
            field=models.CharField(choices=[('chapter', 'Chapter'), ('teens', 'Teens Wing'), ('national_board', 'National Board'), ('senate', 'DPL Senate'), ('organisation', 'Organisation')], default='chapter', max_length=20),
        ),
    ]
