# Generated by Django 4.2.16 on 2026-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_seed_about_menu_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentbranch',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
