# Generated by Django 4.2.16 on 2026-05-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='EvidenceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=100)),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('invoice', 'Invoice'), ('attendance', 'Attendance'), ('media_link', 'Media Link'), ('other', 'Other')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['project_type', 'evidence_type'],
                'unique_together': {('project_type', 'evidence_type')},
            },
        ),
    ]
