# Generated by Django 4.2.16 on 2026-09-24 11:30

from django.db import migrations, models
import dpl.storage


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_notification_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevidence',
            name='file',
            field=models.FileField(blank=True, null=True, storage=dpl.storage.private_storage, upload_to='project_evidence/'),
        ),
    ]
