name: Deploy to cPanel via Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python (optional, only needed if you run Django commands in the workflow)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies (optional, only needed for local testing)
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      # Step 4: Set up SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa.dpl_no_passphrase
          chmod 600 ~/.ssh/id_rsa.dpl_no_passphrase
          ssh-keyscan -p 1980 ftp.dpl.org.np >> ~/.ssh/known_hosts

      # Step 5: Deploy with Git
      - name: Git Pull on cPanel
        run: |
          ssh -i ~/.ssh/id_rsa.dpl_no_passphrase -p 1980 dplorgnp@ftp.dpl.org.np << 'EOF'
          cd /home4/dplorgnp/public_html/dynamic_public_library/
          git pull origin main
          EOF

      # Step 6: Restart the app by touching passenger_wsgi.py
      - name: Restart Python app via Passenger (touch passenger_wsgi.py)
        run: |
          ssh -i ~/.ssh/id_rsa.dpl_no_passphrase -p 1980 dplorgnp@ftp.dpl.org.np << 'EOF'
          touch /home4/dplorgnp/public_html/dpl/passenger_wsgi.py
          EOF
