name: Deploy to cPanel via Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python (optional, only needed if you run Django commands in the workflow)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies (optional, only needed for local testing)
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      # Step 4: Trigger Git Pull on cPanel Server
      - name: Trigger Git Pull on cPanel
        run: |
          ssh ${{ secrets.CPANEL_SSH_USERNAME }}@$${{ secrets.CPANEL_SSH_HOST }} << 'EOF'
          cd /home4/dplorgnp/public_html/dynamic_public_library/
          git pull origin main
          EOF
